
C_FOLDS = 'folds'
C_SHOWS = 'shows'
C_UNCALLED_BET = 'Uncalled bet'
C_RAISES = 'raises'
C_BETS = 'bets'
C_COLLECTED = 'collected'
C_CALLS = 'calls'
C_CHECKS = 'checks'
C_POSTS_BIG_BLIND = 'posts big blind'
C_POSTS_SMALL_BLIND = 'posts small blind'
C_POSTS_SMALL_AND_BIG_BLIND = 'posts small & big blinds'

C_HOLDEM = "Hold'em"
C_ZOOM = 'Zoom'
C_2CENT = '0.02'
C_5CENT = '0.05'
C_10CENT = '0.10'
C_NO_LIMIT = 'No Limit'
C_POT_LIMIT = 'Pot Limit'
C_FIZED_LIMIT = 'Fixed Limit'

C_HOLE_CARDS = 'HOLE CARDS'
C_FLOP = 'FLOP'
C_TURN = 'TURN'
C_RIVER = 'RIVER'
C_SHOW_DOWN = 'SHOW DOWN'
